version: "3.9"

services:
   apache:
      build:
          context: .
          dockerfile: ./docker/apache.Dockerfile
      container_name: apache
      init: true
      ports:
         - 8000:80
      stdin_open: true
      tty: true

   nginx:
      build:
          context: .
          dockerfile: ./docker/nginx.Dockerfile
      container_name: nginx
      init: true
      ports:
         - 8001:80
      stdin_open: true
      tty: true