version: "3.9"

services:
   nginx:
      build: .
      container_name: nginx
      init: true
      ports:
         - 8081:80
      volumes:
         - .:/home/backend
      stdin_open: true
      tty: true

   apache:
      build: .
      container_name: apache
      init: true
      ports:
         - 8082:80
      volumes:
         - .:/var/www/moviology
      stdin_open: true
      tty: true
